# Date range for data download
start_date: '2020-10-10'
end_date: '2025-08-28'

# ticker classes

stock_tickers:
 - AAPL
 - GOOGL
 - META
 - TSLA
 - TGT
 - SBUX
 - WBA
 - RGTI
 - BLCN
 - WMT
 - F
 - IBM
 - MCD
 - GM
 - VZ
 - T


etf_tickers:
 - BLCN
 - URA
 - XSD
 - FPX
 - AADR
 - QTUM
 - PSI
 - ARKW
 - BLOK
 - QQQ






crypto_tickers:
 - BTC-USD
 - ETH-USD
 - XRP-USD
 - USDT-USD
 - BNB-USD
 - SOL-USD
 - USDC-USD
 - STETH-USD
 - TRX-USD



#assets combined
combined_assets:
 - AAPL
 - GOOGL
 - META
 - TSLA
 - TGT
 - SBUX
 - WBA
 - RGTI
 - BLCN
 - WMT
 - F
 - IBM
 - MCD
 - GM
 - VZ
 - T
 - BLCN
 - URA
 - XSD
 - FPX
 - AADR
 - QTUM
 - PSI
 - ARKW
 - BLOK
 - BTC-USD
 - ETH-USD
 - XRP-USD
 - USDT-USD
 - BNB-USD
 - SOL-USD
 - USDC-USD
 - STETH-USD
 - LINK-USD
 - TRX-USD







#risk-free rate (very safe assets like treasury bonds)
risk_free_rate: 0.0092



#ticker for sp500
sp500_ticker: ^GSPC



#for single index model
sim_tickers:
 - AAPL
 - MSFT
 - GOOGL
 - META
 - TSLA
 - TGT
 - SBUX
 - WBA
 - RGTI
 - BLCN
 - WMT
 - F
 - IBM
 - MCD
 - GM
 - VZ
 - T
 - ^GSPC










