# Date range for data download
<<<<<<< HEAD
start_date: '2020-10-15'
end_date: '2025-10-15'
=======
start_date: '2020-10-10'
end_date: '2025-09-10'
>>>>>>> cfa7ff10c9bc118b312e95803c0ad34bea659972

# ticker classes

stock_tickers:
 - AAPL
 - MSFT
 - TGT
 - GM
 - F
 - WMT
 - MCD
 - SBUX
 - TSLA
 - GOOGL



etf_tickers:
- SPY
- QQQ
- VTI
- VOO
- ARKK
- IWM
- DIA
- XLF
- XLK
- EFA







crypto_tickers:
 - BTC-USD
 - ETH-USD
 - XRP-USD
 - USDT-USD
 - BNB-USD
 - SOL-USD
 - USDC-USD
 - STETH-USD
 - TRX-USD
 - LINK-USD


#assets combined
combined_assets:
 - AAPL
 - MSFT
 - TGT
 - GM
 - F
 - WMT
 - MCD
 - SBUX
 - TSLA
 - GOOGL
 - SPY
 - QQQ
 - VTI
 - VOO
 - ARKK
 - IWM
 - DIA
 - XLF
 - XLK
 - EFA
 - BTC-USD
 - ETH-USD
 - XRP-USD
 - USDT-USD
 - BNB-USD
 - SOL-USD
 - USDC-USD
 - STETH-USD
 - TRX-USD
 - LINK-USD
 - ^GSPC






#risk-free rate (very safe assets like treasury bonds)
risk_free_rate: 0.0092



#ticker for sp500
sp500_ticker: ^GSPC





# paths to market data
all_data_path: data/raw/all_prices.csv
stock_data_path: data/raw/stocks.csv
etf_data_path: data/raw/etfs.csv
crypto_data_path: data/raw/crypto.csv
sp500_data_path: data/raw/sp500.csv
# returns path
returns_path: data/processed/returns.csv





