# Date range for data download
start_date: '2020-10-10'
end_date: '2025-08-14'

# ticker classes

stock_tickers:
 - AAPL
 - NVDA
 - MSFT
 - GOOGL
 - META
 - TSLA
 - JPM
 - AVGO
 - WMT
 - V
 - NFLX



etf_tickers:
 - SPY
 - IVV
 - VTI
 - QQQ
 - VUG
 - BND



crypto_tickers:
 - BTC-USD
 - XPR-USD
 - ADA-USD
 - SOL-USD
 - DAI-USD
 - MATIC-USD



# all tickers

all_tickers:
 - AAPL
 - NVDA
 - MSFT
 - GOOGL
 - META
 - TSLA
 - SPY
 - IVV
 - VTI
 - QQQ
 - VUG
 - BND
 - BTC-USD
 - XPR-USD
 - ADA-USD
 - SOL-USD
 - DAI-USD
 - MATIC-USD








#risk-free rate (very safe assets like treasury bonds) I will use TIP
risk_free_rate: 0.005



#ticker for sp500
sp500_ticker: ^GSPC



#for single index model
sim_tickers:
 - AAPL
 - NVDA
 - MSFT
 - GOOGL
 - META
 - TSLA
 - JPM
 - AVGO
 - WMT
 - V
 - NFLX
 - ^GSPC



# path to data with all tickers
all_data_path: data/raw/portfolio.csv
stock_data_path: data/raw/stocks.csv
etf_data_path: data/raw/etf.csv
crypto_data: data/raw/crypto.csv
sp500_data: data/raw/sp500.csv










